git:
  depth: 3

language: cpp

compiler:
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

addons:
  apt:
    packages:
      - clang
      - ninja-build

install:
  - bash ./.travis/install.sh

script:
  - bash ./.travis/run.sh
